### ISSUE TITLE
Unable to pass dynamic props

### ISSUE THREAD

**Issue by sumit-chowjar** [alexjoverm/v-runtime-template#13] opened 2018-10-25 13:09 UTC
Hi,
Thanks for this amazing package.

I was unable to pass props with dynamic component:

```html
<template>
    <div>
        <v-runtime-template :template="template"></v-runtime-template>
    </div>
</template>
<script>
    export default {
        data() {
            return {
                template: `<hero-component :message="'hello'" class="css-class"/>`
            }
        }
    }
</script>
```

`<hero-component>` never recieves `message` prop value, however i can see `class` is being pulled.

**Comment by Pyro979** [comment] 2018-12-27 20:38
@sumit-chowjar, I'm not the maintainer, but how sure are you this was a problem with the template and not the "hero-component". I just tested it on my use case and it worked seemed to work. 

If you're still having an issue, can you post the definition of **hero-component**, and if the issue is resolved, please close it. Thanks.

**Closed** 2019-02-13 10:23 UTC
